# config/config.yaml
server:
  port: 3002

db:
  host: localhost
  port: 3306
  user: root
  password: 123456
  name: tdl

redis:
  host: localhost
  port: 6379
  password: ""

es:
  url: http://localhost:9200

mongodb:
  uri: mongodb://localhost:27017
  database: tdl

rabbitmq:
  username: user
  password: 123456

jwt:
  secret: "your-secret-key-here"
  expiry: 24h  # 24小时有效期

logging:
  level: info
  format: json
  output: stdout

cors:
  allowOrigins:
    - "*"
  allowMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowHeaders:
    - Origin
    - Content-Type
    - Accept
    - Authorization